on:
  pull_request:
    paths:
      - .github/workflows/artifact-attestations.yaml
  workflow_dispatch:

jobs:
  attestation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        num: [0, 1, 2, 3, 4, 5, 6, 7, 9]

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - run: echo "Hello World!" > hello${{ matrix.num }}.txt

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "*.txt"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: hello${{ matrix.num }}.txt
