name: CI
on:
  push:

jobs:
  job1:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  job2:
    needs: [job1]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.job1.result }}"
  
