name: CI
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1.9.2
        with:
          perl-version: '5.14'
      - run: perl -MIO::Socket::SSL -e1
