name: CI
on:
  push:

jobs:
  printInputs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: where make
        shell: cmd
      - run: where gmake
        shell: cmd
      - run: where dmake
        shell: cmd
