
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - run: perl -V
      - run: perl -V
        shell: bash
      - run: env
        shell: bash
