
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        set -x
        git config --list
    - uses: actions/actions-cfn-lint@1bef48b3277ece13805a5b2eb624943cfab63e30
