name: CI
on:
  push:

jobs:
  printInputs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.24"
          distribution: strawberry
      - run: perl -MConfig -E 'say $Config{make}'
