name: CI
on:
  push:

jobs:
  printInputs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: make --version
      - run: gmake --version
      - run: dmake --version
