name: release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS
        uses: fuller-inc/actions-aws-assume-role@v1.3.0-beta1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/github-action-test
          role-session-tagging: true
      - run: aws sts get-caller-identity
