name: release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-upload-release-asset@v0.0.6
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: |
          .github/workflows/*.yml
