name: release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - id: gen
        uses: shogo82148/actions-github-app-token@v0
      - run: |
          gh issue create --title "I found a bug" --body "Nothing works"
          echo "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.gen.outputs.token }}
