name: tmate

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: "OS"
        required: true
        default: "ubuntu-latest"
        options:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "ubuntu-18.04"
          - "windows-2022"
          - "windows-2019"
          - "macos-13"
          - "macos-12"
          - "macos-11"

jobs:
  one:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: mxschmitt/action-tmate@v3
