name: token permission
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1.16.0
        with:
          auto-start: true
          distribution: 'mysql'
          mysql-version: '8.0'
          my-conf: |
            default-authentication-plugin=mysql_native_password
            sync_binlog=0
            innodb_doublewrite=OFF
            innodb-flush-log-at-trx-commit=0
            innodb-flush-method=nosync
          user: user
          root-password: root
          password: password

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
