name: token permission
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: ${{ env.MYSQL_ROOT_PASSWORD }}
          my-cnf: |
            secure-file-priv = ''
            character-set-server = utf8mb4
            collation-server = utf8mb4_0900_ai_ci
            sql-mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
