name: token permission
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh api "repos/$GITHUB_REPOSITORY/actions/secrets/public-key"
        env:
          GITHUB_TOKEN: ${{ github.token }}
#       - run: printenv GITHUB_TOKEN > token
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3
