on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  printInputs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: "ls -la ~/"
        shell: bash
      - run: "cat ~/.bashrc || :"
        shell: bash
      - run: "cat ~/.bash_profile || :"
        shell: bash
