name: token permission
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: gh api "repos/$GITHUB_REPOSITORY" | jq .permissions.push
        env:
          GITHUB_TOKEN: ${{ github.token }}
